const Portfolio_data = [
  {
    id: 1,
    category: "Wallpaper App",
    link:"https://github.com/Richard22Ejike/wallpaperapp ",
    description:"Make the most of your display with beautiful wallpapers and basic features. Choose one of your own photos, an image from the collection.",
    description1:"the wallpaper App was designed using flutter and the pixel pictures api",
    title: " beautiful wallpapers ",
    image: "./image/wallpaper.png",
  },
  {
    id: 2,
    category: "Lumpre",
    link:"https://www.lumpre.com/ ",
    description:"LUMPRE is a marine and engineering services company that provides a wide range of marine services. well-known for the quality and reliability of our vessels and equipment.",
    description1:"I build the website using bootstrap css,Html,javascript, and css",
    title: "LUMPRE Website (marine and engineering services company) ",
    image: "./image/lumpre.png",
  },
  {
    id: 3,
    category: "Weather App",
    link:"https://github.com/Richard22Ejike/Weather-App",
    description:"Get the weather forecast in a beautiful and powerful app. See current and forecasted weather with a smart layout that updates as conditions change.",
    description1:"the weather App was designed using flutter and open weather api",
    title: " weather forecast in a beautiful and powerful app ",
    image: "./image/weather.png",
  },
  {
    id: 4,
    category: "Stopwatch",
    link:"https://github.com/Richard22Ejike/Stopwatch",
    description:"Hybrid Stopwatch and Timer is a simple, easy and accurate app for android that will help you to measure the time of any situation, like sports, cooking, games, education,",
    description1:"the Stopwatch App was designed using flutter and stop watch timer plugin",
    title: "Hybrid Stopwatch and Timer is a simple, easy and accurate app for android",
    image: "./image/stopwatch.png",
  },
  {
    id: 5,
    category: "ToDo App",
    link:"https://github.com/Richard22Ejike/notes",
    description:"a task management app to help you stay organized and manage your day-to-day. You can use this app to make shopping lists or task lists, take notes, record collections, plan an event, or set reminders to increase your productivity and focus on what matters to you. ",
    description1:"the ToDo App was designed using flutter and sqlite database",
    title: "a task management app to help you stay organized",
    image: "./image/note.png",
  },
  {
    id: 6,
    category: "Cryptowatch",
    link:"https://github.com/Richard22Ejike/crytowatch",
    description:"Crypto tracking for 100+ crypto coins with a beautiful UI build that displays the current price, the change in price and the percent change in price",
    description1:"the Cryptowatch App was designed using flutter and coingecko api",
    title: "Crypto tracking for 100+ crypto coins",
    image: "./image/blockchain.png",
  },
]
export default Portfolio_data
